### ISSUE TITLE
Nested array of tables are not supported

### ISSUE THREAD

**Issue by Kripth** [Kripth/toml#8]
```toml
[[fruit]]
  name = "apple"

  [fruit.physical]
    color = "red"
    shape = "round"

  [[fruit.variety]]
    name = "red delicious"

  [[fruit.variety]]
    name = "granny smith"

[[fruit]]
  name = "banana"

  [[fruit.variety]]
    name = "plantain"
```
